import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRuntime,stateMachinePorts} from '../index.js';
import {validateActivitySpec} from '@interactive-project/protocol/validation';
import {validateAction,validateResult} from '@interactive-project/protocol/validation/interoperability';
import {validateEvent} from '@interactive-project/events/validation';
import {createRegistry} from '@interactive-project/registry';
import {validateEngineManifest,validateRendererManifest} from '@interactive-project/registry/validation';
const uuid=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const activity={protocolVersion:'1.0.0',id:uuid(1),type:'interactive-project/quiz',activitySchemaVersion:'0.0.1',metadata:{title:'Lifecycle fixture'},config:{expectedAnswer:'A'}};
const validators={activity:validateActivitySpec,action:validateAction,result:validateResult,event:validateEvent};
const result=(context,revision,score)=>({protocolVersion:'1.0.0',resultVersion:'1.0.0',...context.identity,revision,status:'completed',evidence:[],score:{value:score,scale:'normalized'}});
const reducer={initialState:()=>({answer:null}),reduce:(state,action,context)=>action.type==='fixtures/select'&&typeof action.payload.answer==='string'?{accepted:true,state:{answer:action.payload.answer,random:context.random()}}:{accepted:false},evaluate:(state,ctx,revision)=>result(ctx,revision,state.answer==='A'?1:0)};
const machine=stateMachinePorts({initial:()=>({value:'ready',answer:null}),transition:(state,action,context)=>({value:'answered',answer:action.payload.answer,random:context.random()}),evaluate:(state,ctx,revision)=>result(ctx,revision,state.answer==='A'?1:0)});
function options(ports){let next=100;return{activity,sessionId:uuid(2),attemptId:uuid(3),sourceId:uuid(4),engineId:'fixtures/quiz',engineStateVersion:'0.0.1',clock:()=>1234,random:()=>0.25,nextEventId:()=>uuid(next++),validators,ports};}
const action=(sequence=0)=>({protocolVersion:'1.0.0',actionVersion:'1.0.0',id:uuid(200+sequence),activityId:activity.id,sessionId:uuid(2),attemptId:uuid(3),sequence,type:'fixtures/select',payload:{answer:'A'}});
const histories=[];
for(const ports of [reducer,machine]){
 const diagnostics=[],runtime=createRuntime({...options(ports),onDiagnostic:d=>diagnostics.push(d.code)}),phases=[],events=[];
 runtime.subscribe(v=>phases.push(v.lifecycle));runtime.subscribe(()=>{throw Error('Observer failed');});
 runtime.subscribeEvents(e=>events.push(e.type),{replay:true});
 assert.equal(runtime.getState().lifecycle,'created');assert(Object.isFrozen(runtime.getState().state));assert.throws(()=>runtime.pause(),e=>e.code==='runtime.lifecycle');
 runtime.start();assert.equal(runtime.getState().lifecycle,'active');
 assert.equal(runtime.dispatch(action()).status,'accepted');assert.equal(runtime.getState().revision,1);assert.equal(runtime.getState().state.random,0.25);
 assert.equal(runtime.dispatch(action()).code,'action.stale');
 runtime.pause();assert.equal(runtime.dispatch(action(1)).code,'action.invalid');assert.equal(runtime.evaluate().score.value,1);runtime.resume();
 runtime.subscribe(v=>{if(v.lifecycle==='completed')assert.equal(runtime.dispatch(action(1)).code,'action.busy');});
 runtime.complete();assert.equal(runtime.getState().lifecycle,'completed');assert.equal(runtime.getState().result.score.value,1);
 assert.throws(()=>runtime.start(),e=>e.code==='runtime.lifecycle');
 runtime.dispose();runtime.dispose();assert.equal(runtime.getState().lifecycle,'disposed');assert.equal(runtime.dispatch(action(1)).code,'action.disposed');
 assert.throws(()=>runtime.subscribe(()=>{}),e=>e.code==='runtime.disposed');assert.throws(()=>runtime.serialize(),e=>e.code==='runtime.snapshotUnavailable');
 assert(diagnostics.includes('runtime.observer'));histories.push({phases,events});
}
assert.deepEqual(histories[0],histories[1],'Reducer and state-machine adapters have identical lifecycle/event traces');
const atomic=createRuntime(options({...reducer,reduce:()=>({accepted:true,state:{unsafe:()=>{}}})}));atomic.start();const before=atomic.getState();assert.throws(()=>atomic.dispatch(action()),e=>e.code==='runtime.nonJson');assert.equal(atomic.getState(),before);atomic.dispose();
const broken=createRuntime(options({...reducer,reduce:()=>{throw Error('private native exception');}}));broken.start();assert.throws(()=>broken.dispatch(action()),e=>e.code==='runtime.engine'&&!e.message.includes('private'));assert.equal(broken.getState().revision,0);broken.dispose();
const cancelled=new AbortController(),cancelRuntime=createRuntime(options(reducer));cancelRuntime.start();cancelled.abort();assert.throws(()=>cancelRuntime.dispatch(action(),{signal:cancelled.signal}),e=>e.code==='runtime.cancelled');assert.equal(cancelRuntime.getState().revision,0);assert.equal(cancelRuntime.dispatch(action()).status,'accepted');cancelRuntime.dispose();
const during=new AbortController(),cancelDuring=createRuntime(options({...reducer,reduce:()=>{during.abort();return{accepted:true,state:{answer:'A'}};}}));cancelDuring.start();assert.throws(()=>cancelDuring.dispatch(action(),{signal:during.signal}),e=>e.code==='runtime.cancelled');assert.equal(cancelDuring.getState().revision,0);cancelDuring.dispose();
const disposeDuring=createRuntime(options(reducer));let cleanup=0;const d=createRuntime(options({...reducer,dispose:()=>cleanup++}));d.start();d.subscribe(v=>{if(v.lifecycle==='completed')d.dispose();});d.complete();assert.equal(d.getState().lifecycle,'disposed');d.dispose();assert.equal(cleanup,1);disposeDuring.dispose();
const failed=createRuntime(options(reducer));failed.start();failed.fail();assert.equal(failed.getState().lifecycle,'failed');assert.throws(()=>failed.evaluate(),e=>e.code==='runtime.lifecycle');failed.dispose();
const pending=createRuntime(options({...reducer,evaluate:(state,ctx,revision)=>({protocolVersion:'1.0.0',resultVersion:'1.0.0',...ctx.identity,revision,status:'pending',evidence:[],pendingReason:'response'})}));pending.start();assert.equal(pending.evaluate().status,'pending');assert.throws(()=>pending.complete(),e=>e.code==='runtime.pending');assert.equal(pending.getState().lifecycle,'active');pending.dispose();
const mismatch=createRuntime(options({...reducer,evaluate:(state,ctx,revision)=>({...result(ctx,revision,1),sessionId:uuid(999)})}));mismatch.start();assert.throws(()=>mismatch.evaluate(),e=>e.code==='runtime.result');mismatch.dispose();
const asynchronous=createRuntime(options({...reducer,reduce:async()=>{throw Error('Async unsupported');}}));asynchronous.start();assert.throws(()=>asynchronous.dispatch(action()),e=>e.code==='runtime.async');await new Promise(r=>setImmediate(r));asynchronous.dispose();
const registry=createRegistry({validateEngineManifest,validateRendererManifest}),entry={type:activity.type,activitySchemaVersion:'0.0.1',schemaId:'urn:fixtures:quiz',capabilities:Object.fromEntries(['interactive','evaluable','collaborative','offline','deterministic','resumable','aiGeneratable'].map(c=>[c,{supported:['interactive','evaluable','offline','deterministic'].includes(c)}])),requiredCapabilities:['interactive'],requiredPermissions:[]};
assert(registry.registerEngine({manifestVersion:'1.0.0',id:'fixtures/core-quiz',pluginVersion:'0.0.1',type:activity.type,protocolVersions:['1.0.0'],entries:[entry]},{createEngine:()=>createRuntime(options(reducer)),evaluate:session=>session.evaluate()}).registered);
const found=registry.lookupEngine({type:activity.type,protocolVersion:'1.0.0',activitySchemaVersion:'0.0.1'});assert(found.found);const registered=found.registration.createEngine(activity,{sessionId:uuid(2)});registered.start();registered.dispatch(action());assert.equal(found.registration.evaluate(registered).score.value,1);registered.dispose();registry.dispose();
const source=readFileSync(new URL('../index.js',import.meta.url),'utf8');assert(!/Date\.now|Math\.random|from ['"](?:react|vue|svelte|xstate)|document|window/.test(source));
const ts=(await import('typescript')).default,program=ts.createProgram([new URL('./type-consumer.mts',import.meta.url).pathname],{strict:true,noEmit:true,module:ts.ModuleKind.NodeNext,moduleResolution:ts.ModuleResolutionKind.NodeNext,lib:['lib.es2022.d.ts']});
const diagnostics=ts.getPreEmitDiagnostics(program);assert.equal(diagnostics.length,0,diagnostics.map(d=>(d.file?d.file.fileName+':'+d.start+': ':'')+ts.flattenDiagnosticMessageText(d.messageText,'\n')).join('\n'));
console.log('Core: reducer/machine lifecycle parity, immutable atomic candidates, clock/random injection, post-commit notifications, cancellation/disposal and registry/Protocol session compatibility passed.');
